### ISSUE TITLE
Modernizr.js conflict when using with jQuery Smooth Scroll function

### ISSUE THREAD

**Issue by ShapesGraphicStudio** [CodyHouse/full-screen-pushing-navigation#1]
Hello,

Great script, I really love the effect.

Unfortunately, I'm having a little issue combining scripts, when I try to add a smooth scroll efect on the page, the smooth scroll won't work unless I do not load modernizr.js.

But if I do not load the modernizr.js, the push navigation does not work anymore.

Any idea on what I could do to make those 2 work along ?

Here's the smooth scroll part I'm using with jQuery jquery-3.2.1.min.js.

```
<script>
var $ja = jQuery.noConflict();
$ja(document).ready(function(){
    $ja(".arrow-wrap").on('click', function(event) {
        if (this.hash !== "") {
            event.preventDefault();
            var hash = this.hash;
            $ja('html, body').animate({
                scrollTop: $ja(hash).offset().top
            }, 800, function(){
                window.location.hash = hash;
            });
        }
    });
});
</script>
```

I tried to load modernizr.js in the head before jquery-3.2.1.min.js in the footer.
I tried to move them to change their order, but no luck yet.

Best regards,
David

**Comment by sebastiano-guerriero** [comment]
Hi! You can remove modernizr, but you should remove also the .no-js class applied to the html

**Comment by ShapesGraphicStudio** [comment]
Hey, damn I missed it in my layout, thought I did not have it.. thanks for that one !!
Best regards,
David
