### ISSUE TITLE
Wordpress theme issues with menu

### ISSUE THREAD

**Issue by jresc** [CodyHouse/full-screen-pushing-navigation#2]
When I create a new page in my WordPress theme the content that should load on that page, does not seem to push over seamlessly when the button is clicked. The content pushes, but it over laps onthe background color rather than disappear quickly. I have tried working on fixing it but the only content that pushes over correctly is the content on the header.php and footer.php. Any content in the middle loaded through a WordPress page does not get pushed correctly.

**Comment by sebastiano-guerriero** [comment]
Hi there 👋I'm afraid it's impossible for us to check for bugs or review the code when our resources are part of a complex project.
