### ISSUE TITLE
Want to know how to use it

### ISSUE THREAD

**Issue by Fishhunter2** [CodyHouse/full-screen-pushing-navigation#3]

**Comment by claudia-romano** [comment]
Hi there, we do not support this experiment anymore. But here's an updated version you can use:
https://codyhouse.co/ds/components/app/off-canvas-navigation

Here's the Info page of the component:
https://codyhouse.co/ds/components/info/off-canvas-navigation

And here's the link to the docs on more info on how to use our components:
https://codyhouse.co/ds/get-started

Cheers!
